<?
define('DEVELOPMENT_MODE', FALSE);
define('SHARED_FILENAME', 'shared');
define('FILE_EXTENSION', 'php');
define('APPLICATION_DIRECTORY', 'application');
define('CONTROLLERS_DIRECTORY', 'controllers');

define
(
    'CONTROLLERS_PATH',
    ROOT . DIRECTORY_SEPARATOR .
    APPLICATION_DIRECTORY . DIRECTORY_SEPARATOR . 
    CONTROLLERS_DIRECTORY
);

define('MODELS_DIRECTORY', 'models');

define
(
    'MODELS_PATH',
    ROOT . DIRECTORY_SEPARATOR .
    APPLICATION_DIRECTORY . DIRECTORY_SEPARATOR . 
    MODELS_DIRECTORY
);

define('TEMP_DIRECTORY', 'temp');
define('LOG_DIRECTORY', 'logs');

define
(
    'LOG_PATH',
    ROOT . DIRECTORY_SEPARATOR .
    TEMP_DIRECTORY . DIRECTORY_SEPARATOR .
    LOG_DIRECTORY
);